#!/usr/bin/env bash
#
# gen-memory-status.sh — deterministically regenerate MEMORY-STATUS.md from the
# actual memory files. No model involvement, so it can never emit seed/phantom data.
#
# Usage: gen-memory-status.sh [REPO_ROOT]   (defaults to the git top-level)
#
set -uo pipefail

REPO="${1:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
MEM="$REPO/.claude/memory"

if [ ! -d "$MEM" ]; then
  echo "Error: no .claude/memory at $REPO (run /memory-grounded-review:bootstrap-memory first)." >&2
  exit 1
fi

python3 - "$REPO" <<'PY'
import json, os, re, sys, subprocess, datetime, glob

repo = sys.argv[1]
mem = os.path.join(repo, ".claude", "memory")
now = datetime.datetime.now(datetime.timezone.utc)

def read(p):
    try:
        return open(p, encoding="utf-8").read()
    except Exception:
        return ""

def mtime_days(p):
    try:
        return (now - datetime.datetime.fromtimestamp(os.path.getmtime(p), datetime.timezone.utc)).days
    except Exception:
        return None

def freshness(days):
    if days is None: return "— missing", "🔴"
    if days < 14:  return f"{days}d", "🟢"
    if days <= 45: return f"{days}d", "🟡"
    return f"{days}d", "🔴"

# --- repo name from git remote ---
repo_name = os.path.basename(repo.rstrip("/"))
try:
    url = subprocess.check_output(["git", "-C", repo, "remote", "get-url", "origin"],
                                  stderr=subprocess.DEVNULL).decode().strip()
    m = re.search(r"[:/]([^/:]+/[^/]+?)(?:\.git)?$", url)
    if m: repo_name = m.group(1)
except Exception:
    pass

# --- repo-dna.md ---
dna = read(os.path.join(mem, "repo-dna.md"))
dna_ids = re.findall(r"^-\s*\*\*id:\*\*", dna, re.M)
dna_status = re.findall(r"^-\s*\*\*status:\*\*\s*(\w+)", dna, re.M)
dna_conf = [float(x) for x in re.findall(r"^-\s*\*\*confidence:\*\*\s*([0-9.]+)", dna, re.M)]
dna_total = len(dna_ids)
dna_active = sum(1 for s in dna_status if s == "active")
dna_aging = sum(1 for s in dna_status if s == "aging")

# --- review-memory.md (split out the Archived section) ---
rm = read(os.path.join(mem, "review-memory.md"))
parts = re.split(r"^##\s+Archived\s*$", rm, flags=re.M)
rm_live, rm_archived = parts[0], (parts[1] if len(parts) > 1 else "")
def section(text, header):
    m = re.search(r"^##\s+" + re.escape(header) + r"\s*$(.*?)(?=^##\s+|\Z)", text, re.M | re.S)
    return m.group(1) if m else ""
patterns = section(rm_live, "Review patterns")
prefs = section(rm_live, "Reviewer preferences")
n_patterns = len(re.findall(r"^###\s+", patterns, re.M))
n_prefs = len(re.findall(r"^###\s+", prefs, re.M))
n_archived = len(re.findall(r"^###\s+", rm_archived, re.M))
rm_conf = [float(x) for x in re.findall(r"^-\s*\*\*confidence:\*\*\s*([0-9.]+)", rm_live, re.M)]

# --- architecture-graph.json ---
nodes = edges = high = 0
try:
    g = json.loads(read(os.path.join(mem, "architecture-graph.json")) or "{}")
    nodes = g.get("node_count", len(g.get("nodes", [])))
    edges = g.get("edge_count", len(g.get("edges", [])))
    high = sum(1 for n in g.get("nodes", []) if n.get("risk") == "high")
except Exception:
    pass

# --- pr-index/ ---
pr_files = [f for f in glob.glob(os.path.join(mem, "pr-index", "*.md"))
            if os.path.basename(f).lower() != "readme.md"]
n_prs = len(pr_files)

# --- confidence distribution (active rules + live patterns/prefs) ---
allconf = dna_conf + rm_conf
b1 = sum(1 for c in allconf if c >= 0.85)
b2 = sum(1 for c in allconf if 0.70 <= c < 0.85)
b3 = sum(1 for c in allconf if 0.60 <= c < 0.70)
b4 = sum(1 for c in allconf if c < 0.60)
mean = round(sum(allconf) / len(allconf), 2) if allconf else 0.0
def bar(n, scale=2): return "█" * max(0, n * scale) if n else "·"

# --- freshness rows ---
arts = [
    ("Repository DNA", "repo-dna.md"),
    ("Review Memory", "review-memory.md"),
    ("Architecture Graph", "architecture-graph.json"),
    ("Similar-PR Index", "pr-index"),
    ("Summaries", "summaries"),
]
def overall():
    states = []
    for _, rel in arts:
        d = mtime_days(os.path.join(mem, rel))
        states.append(d)
    if any(d is None for d in states): return "🟡 Needs attention"
    if all(d < 14 for d in states):   return "🟢 Healthy"
    if any(d > 45 for d in states):   return "🔴 Stale — run refresh"
    return "🟡 Aging"

rows = []
for label, rel in arts:
    age, icon = freshness(mtime_days(os.path.join(mem, rel)))
    rows.append(f"| {label} | `.claude/memory/{rel}` | {age} ago | {icon} |")

empty_warn = ""
if n_patterns == 0 and n_prs == 0:
    empty_warn = ("\n> ⚠️ **Review history not yet mined.** `review-memory` and `pr-index` are empty. "
                  "Run `/memory-grounded-review:refresh-memory` to backfill from merged PRs.\n")

out = f"""<!--
  GENERATED FILE — do not edit by hand.
  Produced by scripts/gen-memory-status.sh from the actual .claude/memory/ files.
  Regenerated by /memory-grounded-review:refresh-memory and :update-memory.
-->
# 🧠 Memory-Grounded Review — status

**Repo:** `{repo_name}` · **Generated:** {now:%Y-%m-%d %H:%M} UTC
**Overall health:** {overall()}
{empty_warn}
## Freshness

| Artifact | File | Last refreshed | State |
|---|---|---|---|
{chr(10).join(rows)}

> States: 🟢 fresh (< 14d) · 🟡 aging (14–45d) · 🔴 stale (> 45d).

## Counts

| Metric | Value |
|---|---|
| DNA rules (active) | {dna_active} |
| DNA rules (aging) | {dna_aging} |
| DNA rules (total) | {dna_total} |
| Review patterns | {n_patterns} |
| Reviewer preferences | {n_prefs} |
| Archived entries | {n_archived} |
| Graph nodes / edges | {nodes} / {edges} |
| High-risk nodes | {high} |
| PRs indexed | {n_prs} |

## Confidence distribution (active rules + review patterns)

```
≥ 0.85     {bar(b1):<12} {b1}
0.70–0.85  {bar(b2):<12} {b2}
0.60–0.70  {bar(b3):<12} {b3}
< 0.60     {bar(b4):<12} {b4}
```

**Mean confidence:** {mean} · **scored entries:** {len(allconf)}
"""
open(os.path.join(repo, "MEMORY-STATUS.md"), "w", encoding="utf-8").write(out)
print(f"Wrote {os.path.join(repo, 'MEMORY-STATUS.md')} "
      f"(DNA {dna_total}, patterns {n_patterns}, prefs {n_prefs}, PRs {n_prs}, nodes {nodes})")
PY
